import type { Metadata } from "next";
import TodoForm from "./component/TodoForm";
import './App.css';
import Todos from "./component/Todos";
import TodoSelectAll from "./component/TodoSelectAll";
import TodoFooter from "./component/TodoFooter";

export const metadata: Metadata = {
    title: "Todo List",
    description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="body-todo">
      <div className="todo-app relative mt-32 mb-10 mx-0">
        <TodoForm/>
        <div>
          <main>
            <TodoSelectAll/>
            <Todos/>
          </main>
        </div>
        <TodoFooter/>
      </div>
    </div>
  );
}
